# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - gosec
    - prealloc
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - tests
      - ".*_test\\.go"
  settings:
    errcheck:
      check-blank: false
      # Ignore fire-and-forget writes in proxy (performance critical)
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - io.Copy
        - (*os.File).Write
        - (*os.File).Sync
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gosec:
      excludes:
        # G101: Hardcoded credentials - false positive on URL constants and config templates
        - G101
        # G107: SSRF - false positive on constructed URLs from trusted config
        - G107
        # G204: Subprocess with variable - legitimate CLI commands from trusted agent configs
        - G204
        # G302/G306: File permissions - executables need 0755, hook scripts need 0700
        - G302
        - G306
        # G304: File inclusion - legitimate config file loading for CLI tool
        - G304

formatters:
  enable:
    - gofmt
    - goimports

output:
  show-stats: true
